version: "2"
services:
  dr-web:
    image: nicomiguelino/dr-web
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile.prod
    env_file:
      - ./.env.prod
    expose:
      - 4000
    volumes:
      - sqlite3:/usr/src/database
      - static_volume:/usr/src/app/staticfiles
    tty: true
  dr-nginx:
    image: nicomiguelino/dr-nginx
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile.nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles
volumes:
  sqlite3:
  static_volume:
