FROM debian:buster

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        less \
        python3-dev \
        python3-pip

RUN c_rehash
RUN pip3 install wheel

COPY requirements/requirements.dev.txt /tmp/requirements.dev.txt
RUN pip3 install -r /tmp/requirements.dev.txt

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
