version: "2"
services:
  dr-web:
    image: nicomiguelino/dr-web
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.dev
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
      - "8001:8001"
    tty: true
    volumes:
      - ./:/usr/src/app/
